package havis.llrpservice.sbc.gpio.message;

public enum MessageType {
	GET_CONFIGURATION,
	GET_CONFIGURATION_RESPONSE,
	SET_CONFIGURATION,
	SET_CONFIGURATION_RESPONSE,
	RESET_CONFIGURATION,
	RESET_CONFIGURATION_RESPONSE,
	KEEP_ALIVE,
	CONNECTION_ATTEMPTED,
	STATE_CHANGED
}
