#!/bin/sh

URL="http://admin@localhost/rest/apps"
PKG="50_objenesis.jar 50_cloning.jar 50_xpp3.jar 50_jibx-run.jar 40_havis.util.platform-@PLATFORM@.jar 40_havis.llrpservice-server.jar"

for pkg in $PKG; do
  busybox wget $URL/$pkg/plug -q --spider
done

exit 0